### ISSUE TITLE
Not (yet?) available in maven central

### ISSUE THREAD

**Issue by NiklasMehner** [IBM/eventstreams-java-sdk#2]
The documentation states that the artifact is available from maven-central, but https://repo1.maven.org/maven2/com/ibm/cloud/ does not contain eventstreams_sdk. 

Is publishing the artifact still an open task or am I looking in the wrong location? Can you please check?

Thanks a lot,
  Niklas

**Comment by Malakhit** [comment]
Hi @NiklasMehner - it's still an open task, we're currently working on it. Apologies for the delay.

**Comment by Simon-Clark** [comment]
Hi @NiklasMehner - this is still an open task, yes. Apologies for the delay.

**Comment by JunliWang** [comment]
it is in 
[eventstreams_sdk-adminrest/](https://repo1.maven.org/maven2/com/ibm/cloud/eventstreams_sdk-adminrest/)                                      -         -      
[eventstreams_sdk-oauth-client/](https://repo1.maven.org/maven2/com/ibm/cloud/eventstreams_sdk-oauth-client/)                                   -         -      
[eventstreams_sdk-schemaregistry/](https://repo1.maven.org/maven2/com/ibm/cloud/eventstreams_sdk-schemaregistry/)
